export type IconProps = {
  width?: number;
  height?: number;
  title: string;
  className?: string;
};

export { Camo } from "./Camo";
export { Controller } from "./Controller";
export { CSharp } from "./CSharp";
export { Destiny } from "./Destiny";
export { Disco } from "./Disco";
export { Docker } from "./Docker";
export { Download } from "./Download";
export { Email } from "./Email";
export { Firebase } from "./Firebase";
export { GitHub } from "./GitHub";
export { GraphQL } from "./GraphQL";
export { Gym } from "./Gym";
export { LinkedIn } from "./LinkedIn";
export { Minecraft } from "./Minecraft";
export { MongoDB } from "./MongoDB";
export { NodeJS } from "./NodeJS";
export { Postgres } from "./Postgres";
export { Profile } from "./Profile";
export { Python } from "./Python";
export { ReactLogo } from "./ReactLogo";
export { Redstone } from "./Redstone";
export { TypeScript } from "./TypeScript";
export { Unity } from "./Unity";
export { University } from "./University";
export { Vite } from "./Vite";
